### ISSUE TITLE
process.env.PWD on Windows 10 is undefined 

### ISSUE THREAD

**Issue by jmaes12345** [laxsrbija/chromedriverdl#1]
When running on Windows, I get the following error:

```
Installed Chrome has version 89.0.4389.90
Downloading ChromeDriver 89.0.4389.23 for win32...
internal/validators.js:117
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.normalize (path.js:266:5)
    at Object.Extract (.......\node_modules\unzipper\lib\extract.js:12:33)
    at ClientRequest.<anonymous> (.......\node_modules\chromedriverdl\utils.js:24:52)

```

This appears to be caused by process.env.PWD being undefined in my environment (a known "feature" of node on Windows).

It would be better to use `process.cwd()` to avoid this, as this command always returns a value.

It would also be nice to be able to pass in the path for the destination rather than only allowing the current directory, as this would avoid this issue.

**Comment by laxsrbija** [comment]
Thanks for the heads up. I will look it up and release a patch soon.

**Comment by laxsrbija** [comment]
This should be fixed, though I haven't been to test it since I don't have a Windows machine.

I've also included the [optional parameter](https://github.com/laxsrbija/chromedriverdl#options) for specifying the download destination. 
Here's sample usage: `chromedriverdl -d ~/Desktop`

**Comment by jmaes12345** [comment]
Awesome! I'll try out the new version as soon as I can 😄
